### ISSUE TITLE
Me gustaría colaborar con la traducción al Español! (Argentina)

### ISSUE THREAD

**Issue by n00b2h4ck3r** [BadWolf-alfa/MIUIPRO-XML-MIUI10-SPANISH#1]
Hola, me gustaría poder colaborar con la traducción al Español!

**Comment by BadWolf-alfa** [comment]
MIUIPRO solo da soporte a es_ES dado que solo hay equipo de desarrollo para es_ES no tienen para es_AR ni es_MX y abria que desarrollar traducion para todos paises latinos en tal caso no uno en concreto.... por lo tanto no es factible, se volverian locos en cierto modo....
