### ISSUE TITLE
Collaborators

### ISSUE THREAD

**Issue by ingbrzy** [BadWolf-alfa/MIUIPRO-XML-MIUI10-SPANISH#2]
add me and MarkH-UK as collaborators to use this translation for xiaomi.eu builds.. thanks

**Comment by ingbrzy** [comment]
@BadWolf-alfa

**Comment by Infante007** [comment]
Como jode que te hagan esperar y no te hagan caso

**Comment by BadWolf-alfa** [comment]
@ingbrzy you added on latest commit to the repo translator, another one no, due to no collaborated.

Issue clossed

**Comment by ingbrzy** [comment]
no.. add me as collaborator in the repository settings - collaborators
same for MarkH-UK - his account is used for our autofix errors like were in my PR.. you have still many of them...

**Comment by BadWolf-alfa** [comment]
Tomorrow i change the repo yo another git, this are with basic files foto miuipro, tomorrow i migrate and create the settings file, right?
